export const projects = [
    {
        technologies : [],
        title : "Frontend Web Intern",
        period : 'May-Aug-2022',
        image: 'https://crio-directus-assets.s3.ap-south-1.amazonaws.com/bcf8d7c1-09ec-40d6-9e8a-1047648e7e9f.png',
        overview : ' ',
        description : '',
        link: '/',
        category: "Web",
    },
    {
        technologies : [],
        title : "Frontend Web Intern",
        period : 'May-Aug-2022',
        image: 'https://crio-directus-assets.s3.ap-south-1.amazonaws.com/c495b2a5-b525-4a6b-bd2c-8fa4008cdcf1.png',
        overview : ' ',
        description : '',
        link1: '/',
        link2: '/',
        category: "Mobile",
    },
    {
        technologies : [],
        title : "Frontend Web Intern",
        period : 'May-Aug-2022',
        image: 'https://crio-directus-assets.s3.ap-south-1.amazonaws.com/c495b2a5-b525-4a6b-bd2c-8fa4008cdcf1.png',
        overview : ' ',
        description : '',
        link: '/',
        category: "Fontend",
    },
    {
        technologies : [],
        title : "Frontend Web Intern",
        period : 'May-Aug-2022',
        image: 'https://crio-directus-assets.s3.ap-south-1.amazonaws.com/bcf8d7c1-09ec-40d6-9e8a-1047648e7e9f.png',
        overview : ' ',
        description : '',
        link: '/',
        category: "Machine Learning",
    },
    {
        technologies : [],
        title : "Frontend Web Intern",
        period : 'May-Aug-2022',
        image: 'https://crio-directus-assets.s3.ap-south-1.amazonaws.com/bcf8d7c1-09ec-40d6-9e8a-1047648e7e9f.png',
        overview : ' ',
        description : '',
        link: '/',
        category: "Web",
    },
    {
        technologies : ['js', 'vs', 'bb'],
        title : "Frontend Web Intern",
        period : 'May-Aug-2022',
        image: 'https://crio-directus-assets.s3.ap-south-1.amazonaws.com/c495b2a5-b525-4a6b-bd2c-8fa4008cdcf1.png',
        overview : ' ',
        description : '',
        link: '/',
        category: "Web",
    },
];